Mansion by Rooms begins here.

[!<HauntedRoom>@

REQUIRES COMMENTING

@inherits <Room>

@!]
A haunted room is a kind of room. A haunted room has a labyrinth shape called shape. The shape of a haunted room is usually L4/0-0-1-1-1-1. The grid position of a haunted room is usually <0,0,0>.[A haunted room has a number called slime-puddle. The slime-puddle of a haunted room is usually 0.]

Mansion00 is a haunted room. The printed name of Mansion00 is "White Room". "This room is wallpapered white. Indeed, it is just generally extremely white. The bed-sheets are white, the chairs are white, the cobwebs covering everything are white.".
Mansion01 is a pinned haunted room. The printed name of Mansion01 is "[one of]Grand Foyer[or]Entrance Hall[sticky random]". "A giant room lit by a faulty glass chandelier. Expensive portraits line the sides of the room, and although most of the place is in disrepair, the craftsmanship of the fireplace and archways over the doors make it a surprisingly grand sight as a visitor to the mansion.". Stairwell03 is below Mansion01. The shape of Mansion01 is L4/0-0-1-1-0-1.
Mansion02 is a garlic untrappable mandatory creaky haunted room. The printed name of Mansion02 is "Guest Room". "A small room with a giant portrait of someone with your exact appearance, but distinctly not you, resting over a dirty, cobwebbed fireplace. There is a bed resting underneath a small window on one side of the room, furnished with surprisingly clean pink and red heart-shaped pillows and soft bedspread.[one of][line break][variable custom style]Somehow this is even creepier than the rest of this dump.[roman type][line break][or][stopping]". The shape of Mansion02 is L4/0-0-0-0-1-0.
Mansion03 is a creaky haunted room. The printed name of Mansion03 is "[one of]Lounge[or]Sitting Room[or]Living Room[sticky random]". "You aren't totally sure what this room is for, but there are lots of chairs, lots of cobwebs, and a full-colour portrait of a [if futanari fetish is 1]nude woman hanging over the mantle. She has a penis.[otherwise]what at first glance appears to be a mummy hanging over the mantle. A closer look reveals it's actually a rather effeminate man in some sort of stylised padded bondage suit. He's wearing a buttplug.[end if].".
Mansion04 is a creaky haunted room. The printed name of Mansion04 is "Breakfast [one of]Nook[or]Room[sticky random]". "This rather understated room is furnished with a small table and some uncomfortable looking chairs. The woods are visible through a pair of broken, tarnished windows, giving the room just enough natural lighting to really highlight the smashed dishes and scratched, stained tabletop.". The shape of Mansion04 is L4/0-0-1-1-0-1.
Mansion06 is a creaky haunted room. The printed name of Mansion06 is "Kitchen". "A large room filled with long expanses of uninterrupted counter-top. The one in the centre is stained unpleasantly red, and if that wasn't enough, the knife rack near the sink has several conspicuously open slots.". The shape of Mansion06 is L4/0-0-0-1-1-1.[TODO: work on this room description]
Mansion07 is a creaky haunted room. The printed name of Mansion07 is "Dining Room". "This room is obviously some kind of eating area, as the table is still filled with trays of somewhat fresh looking food. Looking around at the haphazardly placed utensils, plates, and chairs, you get the feeling that whomever was eating this meal stopped abruptly, perhaps... when you walked into the room? [one of][or][line break][variable custom style]That was like that the first time I walked in here, right?[roman type][line break][stopping]".
Mansion08 is a creaky mandatory no-roof haunted room. The printed name of Mansion08 is "Dog House". "An enclosed section of cleared land, which is dimly lit by a small lamp hanging off the side of [if mythical creature fetish is 1]an enormous doghouse, which is more than large enough for a human to live in comfortably, let alone a dog. There's even a bed in there! [otherwise]a big dog house, just about large enough for a human to fit inside. [end if]A small sign sticking out of the grass in front of it reads '[DogPetName]'.". The shape of Mansion08 is L4/0-0-0-0-0-1.
DogPetName is a text that varies.
To say PossiblePetName:
	say "[if mythical creature fetish is 1][one of]Joe[or]Dante[or]Brutus[or]Belial[in random order][otherwise][one of]Fluffles[or]Bouncy[or]Darling[or]Tiddles[in random order][end if]".
Mansion11 is a creaky haunted room. The printed name of Mansion11 is "Trophy Room". "A small room lined with various trophies. A closer inspection reveals that the trophies appear to be for things like 'Biggest Booty' and 'Mortal Enslaver of the Century'...".
Mansion13 is a haunted room. Mansion13 is toilets. The printed name of Mansion13 is "[one of]Washroom[or]Bathroom[sticky random]". "A modestly sized bathroom, with solid black wallpaper, black linoleum tiles, a black marble counter-top, and a small toilet with fuzzy black seat cover. A [if watersports fetish is 1]painting of a smartly dressed man rests opposite the toilet. His trousers are unbuttoned and he has his [manly-penis] in hand[otherwise if diaper quest is 1]painting of a smartly dressed woman rests opposite the toilet. She's sitting on a toilet of her own, but thanks to the thick black diaper in between her and the seat, it is clear that none of her [']business['] is making it into the bowl[otherwise]blank picture frame rests opposite the toilet. A huge gash in the back of the canvas almost distracts you from the penis shaped facets in the sink and the bathtub[end if].". The shape of Mansion13 is L4/0-0-1-0-0-0.
Mansion14 is a creaky haunted room. The printed name of Mansion14 is "Mannequin Room". "This room is quite large, but there are no lighting fixtures or windows, leaving most of its features in total darkness. From what you can see, most of the space in this room is occupied by mannequins. Most of them [if diaper quest is 1]are dressed in frilly lacy doll dresses[otherwise]have giant chests, huge hips, or exaggerated lips carved into their face, and although there are cobwebs everywhere, you can't shake the feeling that the makeshift [vagina] drilled into every crotch is there for more than just 'show'[end if]. [if the latex-transformation of the player > 3]You feel... at home here.[otherwise if the bimbo of the player > 12]What a cool place![otherwise]You're pretty creeped out.[end if]".
Mansion15 is a creaky haunted room. The printed name of Mansion15 is "[one of]Ballroom[or][if diaper quest is 1]Bottle[otherwise]Sperm[end if] Room[or]Ballroom[sticky random]". "This room takes up an obscene amount of space, and were this a normal mansion, it would obviously be the place for parties and other large gatherings. A stone statue of a giant [if diaper quest is 1]baby's bottle[otherwise]sperm[end if] occupies the centre of the dance floor, and when you get close to it, you could swear you can hear music playing faintly from somewhere above you.".
Mansion16 is a creaky bossed mandatory important haunted room. The printed name of Mansion16 is "[one of]Red Room[or]Master Bedroom[or]Blood Room[or]Bloody Bedroom[sticky random]". "This room appears to have been recently redecorated. The taste is quite questionable, given everything is a shade of red unfortunately reminiscent of dried blood. [one of]You can't be sure it isn't dried blood, but given the pleasant strawberry aroma that hangs over the room, and the fuzzy handcuffs on the bedside table, it looks to be just a normal bedroom. [or]There is a portrait of an extremely pale skinned man in a cape hanging above the bed. He doesn't have pants on[if diaper quest is 1], and his crotch is flat and featureless like a doll's[end if]... [or]There is a small portrait of what appears to be someone's [if diaper quest is 1]diapered crotch[otherwise]penis[end if] resisting on the bedside table. It looks... used. [sticky random]The covers of the bed are dishevelled, as if recently slept in. [if there is a lipstick collar in the location of the player]A unique looking collar is resting on the bed.[end if]". The shape of Mansion16 is L4/0-0-0-0-1-0.
Mansion17 is a creaky no-roof haunted room. The printed name of Mansion17 is "Terrace". "A wooden pavilion with an intricately carved wooden railing to keep people from falling off. Looking out over the woods from behind it makes you feel like you're in a jail cell.".
Mansion19 is a creaky haunted room. The printed name of Mansion19 is "[one of]Lab[or]Workshop[at random]". "A dusty room containing an assortment of beakers and complicated pipes. There's a surprisingly large space in the middle of the room, where some leather straps are attached to the floor.".
Mansion21 is a creaky haunted room. The printed name of Mansion21 is "[one of]Storm Cellar[or]Basement[sticky random]". "Everything in this room is covered in at least a centimetre of dust and mould. There is what appears to be a cabinet of wooden dildos off to one side of the room, but there are just too many cobwebs for any to be of 'use.'".[TODO: some are of use]
Mansion23 is a garlic no-roof pinned mandatory haunted room. The printed name of Mansion23 is "Hidden Altar". "A collapsed area of the mansion, where the floorboards give way to bare soil, which is a sickly shade of grey, as if the life were slowly being drained out of it. A stone statue of a [if diaper quest is 1]diapered [otherwise if pregnancy fetish is 1]pregnant [end if]woman [if cultist veil is in the location of the player]wearing a black silk veil [end if]rests in the centre of the 'room'. Her legs have been broken off at the knee, so it looks like she's kneeling at the ominous obsidian altar before her[if the charge of the elder altar >= 100]. A dim purple glow emanates from it[end if].". The shape of Mansion23 is L4/0-0-0-0-1-0.
Mansion25 is a mandatory garlic no-roof water-bodied haunted room. The printed name of Mansion25 is "Tranquil Glade". "A set of stairs lead to a small, circular garden, where you find a [if the corruption of the sacred-pool < 60]distinctly... tranquil clearing.[otherwise if the corruption of the sacred-pool < 120]quiet, but distinctly unnerving area.[otherwise]distinctly... lifeless clearing.[end if] The surrounding vegetation is [if the corruption of the sacred-pool < 60]lush and vibrant, and the low canopy of trees above you seems to pulse with life[otherwise if the corruption of the sacred-pool < 120]thin and the low hanging canopy of tree leaves above you seems brittle and a little intimidating[otherwise]either dead or spread thin, and the low hanging tree branches above you are scarred, grey, and bare of leaves[end if]. A pool rests in the centre, with a stone statue standing over the far edge, cradling a slowly trickling bowl of water.". The shape of Mansion25 is L4/0-0-1-1-1-0.
Mansion26 is a creaky no-roof haunted room. The printed name of Mansion26 is "Courtyard". "A circular pavilion lined with statues in varying states of disrepair, of nude men and women. The level of detail on the more intact ones is kind of unnerving[if diaper quest is 0], especially when you look at their genitals[end if]...". The shape of Mansion26 is L4/0-0-1-1-0-1.
Mansion28 is a mandatory garlic haunted room. The printed name of Mansion28 is "Private Library". "A small room with high bookshelves lining the walls. Several empty pedestals occupy the room, while others protect their contents with sturdy looking glass cases. A lip-shaped plaque over the doorway reads 'Before the bite, you will feel lips on your neck.'." The shape of Mansion28 is L4/0-0-1-0-1-1.
Mansion30 is a creaky haunted room. The printed name of Mansion30 is "Loud Room". "A tiny room with windows on every side of the room except the one with the door. There is a bed in the centre of the room, covered in stains and wicked tears, which expose enough of the mattress springs to make sleeping in it out of the question. You can hear a [man of vampiress][']s voice moaning through the walls." The shape of Mansion30 is L4/0-0-0-1-0-0.
Mansion31 is a creaky haunted room. The printed name of Mansion31 is "Quiet Room". "A tiny room where the strange 'noise' of the rest of the mansion is strangely not present, including the creak of your feet on the floorboards. It's unnerving.". The shape of Mansion31 is L4/0-0-1-1-0-1.
Mansion32 is a creaky mandatory haunted room. The printed name of Mansion32 is "Mansion Portal Room". "This room seems rather out of place, with a very futuristic-looking warp portal on the north wall.". The shape of Mansion32 is L4/0-0-0-1-1-1.
Mansion33 is a creaky haunted room. The printed name of Mansion33 is "Old Library". "A large dusty room with high bookshelves lining the walls. It feels like nobody's been in here in years.". The shape of Mansion33 is L4/0-0-1-0-0-0.
Mansion34 is a creaky haunted room. The printed name of Mansion34 is "Occult Room". "A small room decorated with expensive-looking purple rugs and tapestries.". The shape of Mansion34 is L4/0-0-0-1-1-1.
Mansion35 is a haunted room. The printed name of Mansion35 is "Singed Room.". "A small room occupied with charred and burnt furniture. Something stinks.". The shape of Mansion35 is L4/0-0-1-1-0-1.
Mansion36 is a mandatory creaky haunted room. The printed name of Mansion36 is "Statue Room". "[ExamineDesc of MansionScenery01]".

[Hallways]

Mansion12 is a haunted room. The semen-puddle of Mansion12 is usually 1. The printed name of Mansion12 is "Pink [one of]Hallway[or]Corridor[or]Passage[sticky random]". "Every surface of this hallway is soft, pink, and a little... shiny. There are no visible lighting fixtures anywhere, yet, your surroundings are illuminated by a [one of]warm[or]dim[sticky random] glow.". The shape of Mansion12 is L4/0-0-0-1-1-0.
Mansion24 is a haunted room. The printed name of Mansion24 is "Boarded Hallway". "Several of the doorways adjoining this hallway are boarded up, and the walls are carved with ghastly scratches.". The shape of Mansion24 is L4/0-0-1-1-0-0.
Mansion05 is a haunted room. The printed name of Mansion05 is "[one of]Rear[or]Aft[sticky random] [one of]Hallway[or]Corridor[or]Hall[sticky random]". "A cramped hallway lined with harsh contrast paintings of [if diaper quest is 1]diapered torsos. A hint of the scent of urine can be detected in the air[otherwise]male and female genitalia. The air smells thoroughly of sex[end if], and [one of]you could swear there's actually a bit of [if diaper quest is 1]the liquid[otherwise]cum[end if] leaking out of one of the higher frames.[or]if you didn[']t know any better, which you don[']t, you'd say some of the paintings actually wiggled a bit when you entered the room.[sticky random]". The shape of Mansion05 is L4/0-0-0-1-0-1.
Mansion20 is a creaky no-roof haunted room. The printed name of Mansion20 is "Garden". "An overgrown area full of exotic flowers, shrubs, and low-hanging tree branches.". The shape of Mansion20 is L4/0-0-0-1-0-1.
Mansion18 is a haunted room. The printed name of mansion18 is "Clean Hallway". "This hallway's lights are bright, floorboards polished, and its walls practically gleam with the daily attention that must be lavished on them each day. The messiness of the rest of the mansion ends in straight lines along the edges of the hall.".
Mansion29 is a haunted room. The printed name of Mansion29 is "Slanted Hallway". "The edges of this hallway are warped visibly, giving you the feeling of walking through a fun-house mirror.".
Mansion22 is a haunted room. The printed name of Mansion22 is "Secret Passage". "This dark tunnel is quiet, lined with dim purple candles and freshly moved dirt.". The shape of Mansion22 is L4/0-0-1-0-0-1.
Mansion10 is a haunted room. The printed name of Mansion10 is "Peeling Hallway". "This hallway has a way of making you feel cramped and claustrophobic.".
Mansion27 is a no-roof haunted room. The printed name of Mansion27 is "Back Walk". "What probably used to be a well kept garden of fun-shaped bushes and trees is now little more than a creepy bramble full of vaguely human shapes.". The shape of Mansion27 is L4/0-0-0-0-1-1.
Mansion09 is a haunted room. The printed name of Mansion09 is "Dark Hallway". "This hallway has a way of making you feel cramped and claustrophobic.".

[!<mansion:Region>*

REQUIRES COMMENTING

*!]
The Mansion is a region. Mansion00, Mansion01, Mansion02, Mansion03, Mansion04, Mansion05, Mansion06, Mansion07, Mansion08, Mansion09, Mansion10, Mansion11, Mansion12, Mansion13, Mansion14, Mansion15, Mansion16, Mansion17, Mansion18, Mansion19, Mansion20, Mansion21, Mansion22, Mansion23, Mansion24, Mansion25, Mansion26, Mansion27, Mansion28, Mansion29, Mansion30, Mansion31, Mansion32, Mansion33, Mansion34, Mansion35 and Mansion36 are in The Mansion.

Mansion ends here.
